package com.langleon.dsobuildsim.enums.items;

public enum UniqueItemType implements ItemType {
    //amulets
    AMULET_OF_DEFLECTION,
    AMULET_OF_THE_BLACK_KNIGHT,
    AMULET_OF_THE_KRAKEN,
    AMULET_OF_THE_REALMS,
    AMULET_OF_ZEAL,
    ARACHNA_AMULET,
    BRONZE_HELIOS_AMULET,
    DESTRUCTOR_AMULET,
    GOLDEN_HELIOS_AMULET,
    KINGSHILL_NECKLACE,
    NEFATARI_AMULET,
    SARGONS_SHADOW_AMULET,
    SILVER_HELIOS_AMULET,
    SPIRITUAL_TREASURE,

    //cloaks
    CLOAK_OF_HEROES,
    CLOAK_OF_THE_UNDEFEATABLES,
    GWENFARAS_CLOAK,
    HEREDUR_CLOAK,
    KAYLIN_LEFRYES_COAT,
    MEDUAS_CLOAK,
    MERCILESS_TERROR,
    WINTER_FESTIVAL_BAG,

    //belts
    BEARACHS_INSTINCT,
    BELT_OF_ZEAL,
    BRIGAVIK_BELT,

    //rings
    AGATHONS_RING_OF_ORDER,
    ANNIVERSARY_RING,
    ARTAYAS_RING_OF_LIFE,
    BALORS_RING_OF_CHAOS,
    BRIGAVIK_RING,
    DRAGAN_RING,
    DRAGON_EMBLEM_RING,
    FJALNIRS_RING_OF_FROST,
    FYRGONS_RING_OF_FIRE,
    KINGSHILL_EMBLEM_RING,
    MORTIS_RING,
    OCEANUS_RING_OF_POISON,
    RING_OF_CERULEAN_HOPE,
    RING_OF_CRIMSON_DREAD,
    RING_OF_ICY_BARRIERS,
    RING_OF_RENEWAL,
    RING_OF_WINTER,
    RING_OF_ZEAL,
    STELLAR_GOLD_AS_RING,
    STELLAR_GOLD_DMG_RING,
    STELLAR_GOLD_HP_RING,
    STELLAR_GOLD_MS_RING,
    TERRIBLE_FEAR,

    //helmets
    ABYSSAL_TREASURE_HELMET,
    FEARSOME_EXPLORER_HELMET,
    HEREDUR_HELMET,
    KHALY_MASK,
    SPEECHLESS_TERROR,
    STRAW_HAT,

    //shoulders
    ABYSSAL_TREASURE_PAULDRONS,
    ANNIVERSARY_SHOULDERS,
    KHALYS_SHOULDERS,
    ROYAL_PAULDRONS_OF_SINGULARITY,
    TERRIBAL_TRIBUNAL,
    WORLD_DROP_SHOULDERS,

    //torsos
    ARMOR_OF_THE_BLACK_KNIGHT,
    BRIGAVIK_TORSO,
    DESTRUCTOR_TORSO,
    GREAT_TERROR,
    GRIMMAG_TORSO,
    REMINS_BATTLE_HARNESS,
    SIGRISMARRS_ETERNAL_WARD,

    //gloves
    ABYSSAL_TREASURE_GLOVES,
    BRIGAVIK_GLOVES,
    GLOVE_OF_ZEAL,
    GLOVES_OF_THE_BLACK_KNIGHT,
    HERALDS_GLOVES,
    REIGN_OF_TERROR,

    //boots
    BOOTS_OF_THE_BLACK_KNIGHT,
    BRIGAVIK_BOOTS,
    DEADLY_TERROR,
    FIERY_TRACKS_OF_GRIMMAG,
    GORGONSKIN_LEATHER_BOOTS,
    LAPIS_LAZULI_BOOTS,

    //adornments
    AMULET_OF_THE_VANQUISHER,
    ANCIENT_BATTLE_ADORNMENT,
    GRIMMAGS_FLAMING_WRATH,
    SIGRISMARRS_ETERNAL_GRASP,
    STINGER,

    //one hand weapons
    ARACHNA_ONE_HAND,
    DESTRUCTOR_ONE_HAND,
    DESERT_FLAME_WAND,
    END_OF_TIME_ONE_HAND,
    GWENFARA_ONE_HAND,
    MATERI_SCEPTER,
    STAFF_OF_ETERNAL_FLAME,
    STARLIGHT,

    //off hand
    BOOK_OF_CONDEMNATION,
    GORGA_OFF_HAND,
    GWENFARA_OFF_HAND,
    HEREDURS_LOYAL_SHIELD,
    MATERI_BOOK,
    MATERI_ORB,
    RIDDLE,
    ROYAL_TOMB_OF_THE_GUARDIANS,
    SHARR_KHARABS_OFF_HAND,

    //two hand weapons
    ATLANTIS_TWO_HAND,
    BEARACH_TWO_HAND,
    BRIGAVIK_TWO_HAND,
    DRAGANS_TWOHAND,
    DRAGANS_TWOHAND_FIRE,
    DRAGANS_TWOHAND_LIGHTNING,
    DRAGANS_TWOHAND_POISON,
    EXECUTOR,
    GRIMACE_OF_THE_IMMORTAL_BEAST,
    GRIMACE_OF_THE_THUNDERBEAST,
    HERALDS_TWO_HAND,
    MATERI_STAFF,
    PREMIUM_TWO_HAND,
    WORLD_DROP_TWO_HAND,

    ;
}
