package com.langleon.dsobuildsim.items.uniqueitems;

import com.langleon.dsobuildsim.items.core.enums.ItemType;

public enum UniqueItemType implements ItemType {
    //amulets
    AMULET_OF_DEFLECTION,
    AMULET_OF_THE_BLACK_KNIGHT,
    AMULET_OF_THE_KRAKEN,
    AMULET_OF_THE_REALMS,
    AMULET_OF_ZEAL,
    ARACHNA_AMULET,
    BRONZE_HELIOS_AMULET,
    DESTRUCTOR_AMULET,
    GOLDEN_HELIOS_AMULET,
    KINGSHILL_NECKLACE,
    MATERI_AMULET,
    NEFATARI_AMULET,
    SARGONS_SHADOW_AMULET,
    SILVER_HELIOS_AMULET,
    SPIRITUAL_TREASURE,

    //cloaks
    CLOAK_OF_HEROES,
    CLOAK_OF_THE_UNDEFEATABLES,
    GWENFARAS_CLOAK,
    HERALD_CLOAK,
    KAYLIN_LEFRYES_COAT,
    MATERI_CLOAK,
    MEDUSA_CLOAK,
    MERCILESS_TERROR,
    WINTER_FESTIVAL_BAG,

    //belts
    BEARACHS_INSTINCT,
    BELT_OF_ZEAL,
    BRIGAVIK_BELT,
    MATERI_BELT,

    //rings
    AGATHONS_RING_OF_ORDER,
    ANNIVERSARY_RING,
    ARTAYAS_RING_OF_LIFE,
    BALORS_RING_OF_CHAOS,
    BRIGAVIK_RING,
    DRAGAN_RING,
    DRAGON_EMBLEM_RING,
    FJALNIRS_RING_OF_FROST,
    FYRGONS_RING_OF_FIRE,
    KINGSHILL_EMBLEM_RING,
    MATERI_RING,
    MORTIS_RING,
    OCEANUS_RING_OF_POISON,
    RING_OF_CERULEAN_HOPE,
    RING_OF_CRIMSON_DREAD,
    RING_OF_ICY_BARRIERS,
    RING_OF_RENEWAL,
    RING_OF_WINTER,
    RING_OF_ZEAL,
    STELLAR_GOLD_AS_RING,
    STELLAR_GOLD_DMG_RING,
    STELLAR_GOLD_HP_RING,
    STELLAR_GOLD_MS_RING,
    TERRIBLE_FEAR,

    //helmets
    ABYSSAL_TREASURE_HELMET,
    GOLDEN_HORN_CAP,
    HEREDUR_HELMET,
    KHALY_MASK,
    MATERI_MASK,
    SPEECHLESS_TERROR,
    STRAW_HAT,
    WORLD_DROP_HELMET,

    //shoulders
    ABYSSAL_TREASURE_PAULDRONS,
    ANNIVERSARY_SHOULDERS,
    KHALYS_SHOULDERS,
    MATERI_SHOULDERS,
    PREMIUM_SHOULDERS,
    TERRIBAL_TRIBUNAL,
    WORLD_DROP_SHOULDERS,

    //torsos
    ARMOR_OF_THE_BLACK_KNIGHT,
    BRIGAVIK_TORSO,
    DESTRUCTOR_TORSO,
    GREAT_TERROR,
    GRIMMAG_TORSO,
    MATERI_TORSO,
    WORLD_DROP_TORSO,
    SIGRISMARR_TORSO,

    //gloves
    ABYSSAL_TREASURE_GLOVES,
    BRIGAVIK_GLOVES,
    GLOVE_OF_ZEAL,
    GLOVES_OF_THE_BLACK_KNIGHT,
    HERALDS_GLOVES,
    MATERI_GLOVES,
    REIGN_OF_TERROR,

    //boots
    BOOTS_OF_THE_BLACK_KNIGHT,
    BRIGAVIK_BOOTS,
    DEADLY_TERROR,
    GRIMMAG_BOOTS,
    MATERI_BOOTS,
    MEDUSA_BOOTS,
    LAPIS_LAZULI_BOOTS,

    //adornments
    ADORNMENT_OF_THE_VANQUISHER,
    BRIGAVIK_ADORNMENT,
    GRIMMAG_ADORNMENT,
    MATERI_ADORNMENT,
    SIGRISMARRS_ADORNMENT,
    ROCKETMAN_ADORNMENT,

    //one hand weapons
    ARACHNA_ONE_HAND,
    DESTRUCTOR_ONE_HAND,
    DESERT_ONE_HAND,
    DRAKEN_ONE_HAND,
    END_OF_TIME_ONE_HAND,
    GWENFARA_ONE_HAND,
    MATERI_ONE_HAND,
    WORLD_DROP_ONE_HAND,

    //off hand,
    DRAKEN_OFF_HAND,
    GORGA_OFF_HAND,
    GWENFARA_OFF_HAND,
    HEREDURS_OFF_HAND,
    MATERI_OFF_HAND_1,
    MATERI_OFF_HAND_2,
    PREMIUM_OFF_HAND,
    SHARR_KHARABS_OFF_HAND,
    WORLD_DROP_OFF_HAND_1,
    WORLD_DROP_OFF_HAND_2,

    //two hand weapons
    ANNIVERSARY_TWO_HAND,
    ANNIVERSARY_TWO_HAND_UPGRADED,
    ATLANTIS_TWO_HAND,
    BEARACH_TWO_HAND,
    BRIGAVIK_TWO_HAND,
    DRAGANS_TWOHAND_BASE,
    DRAGANS_TWOHAND_FIRE,
    DRAGANS_TWOHAND_LIGHTNING,
    DRAGANS_TWOHAND_POISON,
    EXECUTOR,
    HERALD_TWO_HAND,
    MATERI_TWO_HAND,
    PREMIUM_TWO_HAND,
    WORLD_DROP_TWO_HAND,

    ;
}
