export enum CollectorBagCategory {
    DRAGON_SPAWN = "DRAGON_SPAWN",
    SCOUNDRELS = "SCOUNDRELS",
    DOMESTICATED = "DOMESTICATED",
    WILD_BEASTS = "WILD_BEASTS",
    AQUATICS = "AQUATICS",
    AVIANS = "AVIANS",
    TAMED_FOES = "TAMED_FOES",
    FREE_SPIRITS = "FREE_SPIRITS",
    AUTOMATONS = "AUTOMATONS",
    LUCKY_CATS = "LUCKY_CATS",
    ENIGMATIC_HATCHLINGS = "ENIGMATIC_HATCHLINGS",
    AWOKEN_LION = "AWOKEN_LION",
    ANCIENT_DRAGONS = "ANCIENT_DRAGONS",
    ALCHEMY_CIRCLES = "ALCHEMY_CIRCLES",
    SHADOW_SOULS = "SHADOW_SOULS"
}