export enum CollectorBagBonusType {
    BULWARK_OF_SIX = "BULWARK_OF_SIX",
    RESISTANCE_OF_SIX = "RESISTANCE_OF_SIX",
    SOULBOUND_POWER_1 = "SOULBOUND_POWER_1",
    SOULBOUND_POWER_2 = "SOULBOUND_POWER_2",
    STRENGTH_OF_NINE = "STRENGTH_OF_NINE",
    TRIAD_OF_LIFE = "TRIAD_OF_LIFE",
    WAVING_OF_FORTUNE = "WAVING_OF_FORTUNE",
}