export enum ItemSlot {
    AMULET = "AMULET",
    CLOAK = "CLOAK",
    BELT = "BELT",
    RING1 = "RING1",
    RING2 = "RING2",
    HELMET = "HELMET",
    SHOULDERS = "SHOULDERS",
    TORSO = "TORSO",
    GLOVES = "GLOVES",
    BOOTS = "BOOTS",
    WEAPON_ADORNMENT = "WEAPON_ADORNMENT",
    ONE_HAND_WEAPON = "ONE_HAND_WEAPON",
    OFF_HAND = "OFF_HAND",
    TWO_HAND_WEAPON = "TWO_HAND_WEAPON",
    SOUL_COMPANION_AMULET = "SOUL_COMPANION_AMULET",
    SOUL_COMPANION_CLOAK = "SOUL_COMPANION_CLOAK",
    SOUL_COMPANION_BELT = "SOUL_COMPANION_BELT"
}