export enum WisdomGroupType {
    HEALTH_RESOURCE = "HEALTH_RESOURCE",
    ATTACK = "ATTACK",
    DEFENSE = "DEFENSE",
    COMBAT = "COMBAT",
    ONE_HANDED_WEAPON = "ONE_HANDED_WEAPON",
    TWO_HANDED_WEAPON = "TWO_HANDED_WEAPON",
    PROSPERITY = "PROSPERITY",
    TRAVEL_MERITS = "TRAVEL_MERITS"
}