import com.sun.security.jgss.GSSUtil;
import kaukasus.Character.Character;
import kaukasus.Enchants.Enchant;
import kaukasus.Enchants.UniqueEnchant;
import kaukasus.Enums.*;
import kaukasus.Gems.Gem;
import kaukasus.Gems.Opal;
import kaukasus.Items.MythicItem;
import kaukasus.Items.SetItem;
import kaukasus.Items.UniqueItem;
import kaukasus.Jewels.Jewel;
import kaukasus.Jewels.JewelTrinket;
import kaukasus.OverallBuffs.OverallAbsolutBuff;
import kaukasus.OverallBuffs.OverallBuff;
import kaukasus.OverallBuffs.OverallRelativeBuff;
import kaukasus.Runes.Rune;
import kaukasus.Runes.RuneTrinket;
import kaukasus.Runes.SpecialRune;

import java.util.*;
import java.util.List;

public class RealMageTest {
    public static void main(String[] args) {
        Character mage = testMage();
        printStats(mage.getClassBaseStats());
        System.out.println();
        mage.calculateFinalStats();
        printStats(mage.getCharacterFinalStats());
    }

    public static Character testMage() {
        Character mage = new Character(CharacterClassEnum.SPELLWEAVER);

        Map<AbsoluteStatTypeEnum, Double> amuletBaseStats = new HashMap<>();
        amuletBaseStats.put(AbsoluteStatTypeEnum.CRIT_VALUE, 173.466);
        amuletBaseStats.put(AbsoluteStatTypeEnum.HEALTH_POINTS, 24127.76);
        amuletBaseStats.put(AbsoluteStatTypeEnum.POISON_RESISTANCE, 3412.286);
        Map<AbsoluteStatTypeEnum, Double> amuletUniqueBaseStats = new HashMap<>();
        amuletUniqueBaseStats.put(AbsoluteStatTypeEnum.POISON_RESISTANCE, 3406.0);
        UniqueItem amulet = new UniqueItem("Amulet of the Kraken", ItemTypeEnum.AMULET, amuletBaseStats, amuletUniqueBaseStats, List.of(), List.of());
        amulet.addEnchant(new Enchant(EnchantTypeEnum.HEALTH_POINTS, 0.44537));
        amulet.addEnchant(new Enchant(EnchantTypeEnum.HEALTH_POINTS, 0.44537));
        amulet.addEnchant(new Enchant(EnchantTypeEnum.HEALTH_POINTS, 0.44537));
        amulet.addEnchant(new Enchant(EnchantTypeEnum.HEALTH_POINTS, 0.44537));
        amulet.addGem(new Gem(AbsoluteStatTypeEnum.HEALTH_POINTS, 5500.0));
        amulet.addGem(new Gem(AbsoluteStatTypeEnum.HEALTH_POINTS, 5500.0));
        amulet.addGem(new Gem(AbsoluteStatTypeEnum.HEALTH_POINTS, 5500.0));
        amulet.addGem(new Gem(AbsoluteStatTypeEnum.HEALTH_POINTS, 5500.0));
        amulet.addGem(new Gem(AbsoluteStatTypeEnum.HEALTH_POINTS, 5500.0));
        amulet.addGem(new Gem(AbsoluteStatTypeEnum.HEALTH_POINTS, 5500.0));
        amulet.addGem(new Gem(AbsoluteStatTypeEnum.HEALTH_POINTS, 5500.0));
        amulet.addGem(new Gem(AbsoluteStatTypeEnum.HEALTH_POINTS, 5500.0));
        amulet.addGem(new Gem(AbsoluteStatTypeEnum.HEALTH_POINTS, 5500.0));
        amulet.addGem(new Gem(AbsoluteStatTypeEnum.HEALTH_POINTS, 5500.0));
        mage.addItem(amulet, ItemSlotEnum.AMULET);

        Map<AbsoluteStatTypeEnum, Double> cloakBaseStats = new HashMap<>();
        cloakBaseStats.put(AbsoluteStatTypeEnum.DAMAGE, 1891.513);
        cloakBaseStats.put(AbsoluteStatTypeEnum.ATTACK_SPEED, 0.06);
        cloakBaseStats.put(AbsoluteStatTypeEnum.HEALTH_POINTS, 16507.200);
        List<OverallBuff> cloakOverallBuffs = new ArrayList<>();
        cloakOverallBuffs.add(new OverallRelativeBuff(OverallRelativeBuffTypeEnum.DAMAGE, 0.10));
        cloakOverallBuffs.add(new OverallAbsolutBuff(AbsoluteStatTypeEnum.DAMAGE, 5000.0));
        MythicItem cloak = new MythicItem("Ancestral Glory Cloak (Mage)", ItemTypeEnum.CLOAK, cloakBaseStats, Map.of(), List.of(), cloakOverallBuffs, SetTypeEnum.SET1);
        cloak.addEnchant(new Enchant(EnchantTypeEnum.DAMAGE, 0.44776));
        cloak.addEnchant(new Enchant(EnchantTypeEnum.DAMAGE, 0.44776));
        cloak.addEnchant(new Enchant(EnchantTypeEnum.DAMAGE, 0.44776));
        cloak.addEnchant(new Enchant(EnchantTypeEnum.DAMAGE, 0.44776));
        cloak.addGem(new Gem(AbsoluteStatTypeEnum.DAMAGE, 700.0));
        cloak.addGem(new Gem(AbsoluteStatTypeEnum.DAMAGE, 700.0));
        cloak.addGem(new Gem(AbsoluteStatTypeEnum.DAMAGE, 700.0));
        cloak.addGem(new Gem(AbsoluteStatTypeEnum.DAMAGE, 700.0));
        cloak.addGem(new Gem(AbsoluteStatTypeEnum.DAMAGE, 700.0));
        cloak.addGem(new Gem(AbsoluteStatTypeEnum.DAMAGE, 700.0));
        cloak.addGem(new Gem(AbsoluteStatTypeEnum.DAMAGE, 700.0));
        cloak.addGem(new Gem(AbsoluteStatTypeEnum.DAMAGE, 700.0));
        cloak.addGem(new Gem(AbsoluteStatTypeEnum.DAMAGE, 700.0));
        cloak.addGem(new Gem(AbsoluteStatTypeEnum.DAMAGE, 700.0));
        mage.addItem(cloak, ItemSlotEnum.CLOAK);

        Map<AbsoluteStatTypeEnum, Double> beltBaseStats = new HashMap<>();
        beltBaseStats.put(AbsoluteStatTypeEnum.DAMAGE, 1630.885);
        beltBaseStats.put(AbsoluteStatTypeEnum.HEALTH_POINTS, 20072.654);
        beltBaseStats.put(AbsoluteStatTypeEnum.RESISTANCE, 1679.873);
        UniqueItem belt = new UniqueItem("Belt of Zeal", ItemTypeEnum.BELT, beltBaseStats, Map.of(), List.of(new UniqueEnchant(EnchantTypeEnum.DAMAGE, 0.22384)), List.of());
        belt.addEnchant(new Enchant(EnchantTypeEnum.DAMAGE, 0.44776));
        belt.addEnchant(new Enchant(EnchantTypeEnum.DAMAGE, 0.44776));
        belt.addEnchant(new Enchant(EnchantTypeEnum.DAMAGE, 0.44776));
        belt.addEnchant(new Enchant(EnchantTypeEnum.DAMAGE, 0.44776));
        belt.addGem(new Gem(AbsoluteStatTypeEnum.DAMAGE, 700.0));
        belt.addGem(new Gem(AbsoluteStatTypeEnum.DAMAGE, 700.0));
        belt.addGem(new Gem(AbsoluteStatTypeEnum.DAMAGE, 700.0));
        belt.addGem(new Gem(AbsoluteStatTypeEnum.DAMAGE, 700.0));
        belt.addGem(new Gem(AbsoluteStatTypeEnum.DAMAGE, 700.0));
        belt.addGem(new Gem(AbsoluteStatTypeEnum.DAMAGE, 700.0));
        belt.addGem(new Gem(AbsoluteStatTypeEnum.DAMAGE, 700.0));
        belt.addGem(new Gem(AbsoluteStatTypeEnum.DAMAGE, 700.0));
        belt.addGem(new Gem(AbsoluteStatTypeEnum.DAMAGE, 700.0));
        belt.addGem(new Gem(AbsoluteStatTypeEnum.DAMAGE, 700.0));
        mage.addItem(belt, ItemSlotEnum.BELT);

        Map<AbsoluteStatTypeEnum, Double> ringBaseStats = new HashMap<>();
        ringBaseStats.put(AbsoluteStatTypeEnum.DAMAGE, 1891.513);
        ringBaseStats.put(AbsoluteStatTypeEnum.CRIT_VALUE, 1753.505);
        ringBaseStats.put(AbsoluteStatTypeEnum.HEALTH_POINTS, 24760.80);
        List<OverallBuff> ringOverallBuffs = new ArrayList<>();
        ringOverallBuffs.add(new OverallRelativeBuff(OverallRelativeBuffTypeEnum.DAMAGE, 0.10));
        ringOverallBuffs.add(new OverallRelativeBuff(OverallRelativeBuffTypeEnum.CRIT_VALUE, 0.10));
        MythicItem ring = new MythicItem("Ancestral Glory Ring", ItemTypeEnum.RING, ringBaseStats, Map.of(), List.of(), ringOverallBuffs, SetTypeEnum.SET1);
        ring.addEnchant(new Enchant(EnchantTypeEnum.DAMAGE, 0.44776));
        ring.addEnchant(new Enchant(EnchantTypeEnum.DAMAGE, 0.44776));
        ring.addEnchant(new Enchant(EnchantTypeEnum.DAMAGE, 0.44776));
        ring.addEnchant(new Enchant(EnchantTypeEnum.DAMAGE, 0.44776));
        ring.addGem(new Gem(AbsoluteStatTypeEnum.DAMAGE, 700.0));
        ring.addGem(new Gem(AbsoluteStatTypeEnum.DAMAGE, 700.0));
        ring.addGem(new Gem(AbsoluteStatTypeEnum.DAMAGE, 700.0));
        ring.addGem(new Gem(AbsoluteStatTypeEnum.DAMAGE, 700.0));
        ring.addGem(new Gem(AbsoluteStatTypeEnum.DAMAGE, 700.0));
        ring.addGem(new Gem(AbsoluteStatTypeEnum.DAMAGE, 700.0));
        ring.addGem(new Gem(AbsoluteStatTypeEnum.DAMAGE, 700.0));
        ring.addGem(new Gem(AbsoluteStatTypeEnum.DAMAGE, 700.0));
        ring.addGem(new Gem(AbsoluteStatTypeEnum.DAMAGE, 700.0));
        ring.addGem(new Gem(AbsoluteStatTypeEnum.DAMAGE, 700.0));
        mage.addItem(ring, ItemSlotEnum.RING1);
        mage.addItem(ring, ItemSlotEnum.RING2);

        Map<AbsoluteStatTypeEnum, Double> adornmentBaseStats = new HashMap<>();
        adornmentBaseStats.put(AbsoluteStatTypeEnum.DAMAGE, 1870.52);
        adornmentBaseStats.put(AbsoluteStatTypeEnum.CRIT_VALUE, 2100.146);
        Map<AbsoluteStatTypeEnum, Double> adornmentUniqueBaseStats = new HashMap<>();
        adornmentUniqueBaseStats.put(AbsoluteStatTypeEnum.ATTACK_SPEED, 0.060);
        UniqueItem adornment = new UniqueItem("Sigrismarr's Eternal Grasp", ItemTypeEnum.WEAPON_ADORNMENT, adornmentBaseStats, adornmentUniqueBaseStats, List.of(), List.of());
        adornment.addEnchant(new Enchant(EnchantTypeEnum.DAMAGE, 0.44771));
        adornment.addEnchant(new Enchant(EnchantTypeEnum.DAMAGE, 0.44767));
        adornment.addEnchant(new Enchant(EnchantTypeEnum.DAMAGE, 0.44775));
        adornment.addEnchant(new Enchant(EnchantTypeEnum.DAMAGE, 0.44772));
        Opal opal = new Opal(new Gem(AbsoluteStatTypeEnum.CRIT_VALUE, 2520.0), new Gem(AbsoluteStatTypeEnum.DAMAGE, 700.0), new Gem(AbsoluteStatTypeEnum.MOVEMENT_SPEED, 0.17));
        adornment.addGem(opal);
        adornment.addGem(opal);
        adornment.addGem(opal);
        adornment.addGem(opal);
        adornment.addGem(opal);
        adornment.addGem(opal);
        adornment.addGem(opal);
        adornment.addGem(opal);
        adornment.addGem(opal);
        adornment.addGem(opal);
        mage.addItem(adornment, ItemSlotEnum.WEAPON_ADORNMENT);

        Map<AbsoluteStatTypeEnum, Double> helmetBaseStats = new HashMap<>();
        helmetBaseStats.put(AbsoluteStatTypeEnum.DAMAGE, 1512.772);
        helmetBaseStats.put(AbsoluteStatTypeEnum.CRIT_VALUE, 1394.209);
        helmetBaseStats.put(AbsoluteStatTypeEnum.HEALTH_POINTS, 18258.694);
        SetItem helmet = new SetItem("Sargon's Horns", ItemTypeEnum.HELMET, helmetBaseStats, SetTypeEnum.SET1);
        helmet.addEnchant(new Enchant(EnchantTypeEnum.HEALTH_POINTS, 0.4452));
        helmet.addEnchant(new Enchant(EnchantTypeEnum.HEALTH_POINTS, 0.44364));
        helmet.addEnchant(new Enchant(EnchantTypeEnum.HEALTH_POINTS, 0.44483));
        helmet.addEnchant(new Enchant(EnchantTypeEnum.HEALTH_POINTS, 0.44430));
        helmet.addGem(new Gem(AbsoluteStatTypeEnum.HEALTH_POINTS, 5500.0));
        helmet.addGem(new Gem(AbsoluteStatTypeEnum.HEALTH_POINTS, 5500.0));
        helmet.addGem(new Gem(AbsoluteStatTypeEnum.HEALTH_POINTS, 5500.0));
        helmet.addGem(new Gem(AbsoluteStatTypeEnum.HEALTH_POINTS, 5500.0));
        helmet.addGem(new Gem(AbsoluteStatTypeEnum.HEALTH_POINTS, 5500.0));
        helmet.addGem(new Gem(AbsoluteStatTypeEnum.HEALTH_POINTS, 5500.0));
        helmet.addGem(new Gem(AbsoluteStatTypeEnum.HEALTH_POINTS, 5500.0));
        helmet.addGem(new Gem(AbsoluteStatTypeEnum.HEALTH_POINTS, 5500.0));
        helmet.addGem(new Gem(AbsoluteStatTypeEnum.HEALTH_POINTS, 5500.0));
        helmet.addGem(new Gem(AbsoluteStatTypeEnum.HEALTH_POINTS, 5500.0));
        mage.addItem(helmet, ItemSlotEnum.HELMET);

        Map<AbsoluteStatTypeEnum, Double> shouldersBaseStats = new HashMap<>();
        shouldersBaseStats.put(AbsoluteStatTypeEnum.DAMAGE, 1876.316);
        shouldersBaseStats.put(AbsoluteStatTypeEnum.CRIT_VALUE, 1282.912);
        shouldersBaseStats.put(AbsoluteStatTypeEnum.ANDERMAGIC_RESISTANCE, 3443.896);
        SetItem shoulders = new SetItem("Sargon's Pauldrons", ItemTypeEnum.SHOULDERS, shouldersBaseStats, SetTypeEnum.SET1);
        shoulders.addEnchant(new Enchant(EnchantTypeEnum.DAMAGE, 0.44757));
        shoulders.addEnchant(new Enchant(EnchantTypeEnum.DAMAGE, 0.44766));
        shoulders.addEnchant(new Enchant(EnchantTypeEnum.DAMAGE, 0.44757));
        shoulders.addEnchant(new Enchant(EnchantTypeEnum.DAMAGE, 0.44750));
        shoulders.addGem(new Gem(AbsoluteStatTypeEnum.CRIT_VALUE, 2520.0));
        shoulders.addGem(new Gem(AbsoluteStatTypeEnum.CRIT_VALUE, 2520.0));
        shoulders.addGem(new Gem(AbsoluteStatTypeEnum.CRIT_VALUE, 2520.0));
        shoulders.addGem(new Gem(AbsoluteStatTypeEnum.CRIT_VALUE, 2520.0));
        shoulders.addGem(new Gem(AbsoluteStatTypeEnum.CRIT_VALUE, 2520.0));
        shoulders.addGem(new Gem(AbsoluteStatTypeEnum.CRIT_VALUE, 2520.0));
        shoulders.addGem(new Gem(AbsoluteStatTypeEnum.CRIT_VALUE, 2520.0));
        shoulders.addGem(new Gem(AbsoluteStatTypeEnum.CRIT_VALUE, 2520.0));
        shoulders.addGem(new Gem(AbsoluteStatTypeEnum.CRIT_VALUE, 2520.0));
        shoulders.addGem(new Gem(AbsoluteStatTypeEnum.CRIT_VALUE, 2520.0));
        mage.addItem(shoulders, ItemSlotEnum.SHOULDERS);

        Map<AbsoluteStatTypeEnum, Double> torsoBaseStats = new HashMap<>();
        torsoBaseStats.put(AbsoluteStatTypeEnum.DAMAGE, 1631.657);
        torsoBaseStats.put(AbsoluteStatTypeEnum.HEALTH_POINTS, 14232.794);
        torsoBaseStats.put(AbsoluteStatTypeEnum.ARMOR, 1639.716);
        SetItem torso = new SetItem("Sargon's Torso", ItemTypeEnum.TORSO, torsoBaseStats, SetTypeEnum.SET1);
        torso.addEnchant(new Enchant(EnchantTypeEnum.HEALTH_POINTS, 0.44263));
        torso.addEnchant(new Enchant(EnchantTypeEnum.HEALTH_POINTS, 0.44415));
        torso.addEnchant(new Enchant(EnchantTypeEnum.HEALTH_POINTS, 0.44382));
        torso.addEnchant(new Enchant(EnchantTypeEnum.HEALTH_POINTS, 0.44237));
        torso.addGem(new Gem(AbsoluteStatTypeEnum.HEALTH_POINTS, 5500.0));
        torso.addGem(new Gem(AbsoluteStatTypeEnum.HEALTH_POINTS, 5500.0));
        torso.addGem(new Gem(AbsoluteStatTypeEnum.HEALTH_POINTS, 5500.0));
        torso.addGem(new Gem(AbsoluteStatTypeEnum.HEALTH_POINTS, 5500.0));
        torso.addGem(new Gem(AbsoluteStatTypeEnum.HEALTH_POINTS, 5500.0));
        torso.addGem(new Gem(AbsoluteStatTypeEnum.CRIT_VALUE, 2520.0));
        torso.addGem(new Gem(AbsoluteStatTypeEnum.CRIT_VALUE, 2520.0));
        torso.addGem(new Gem(AbsoluteStatTypeEnum.CRIT_VALUE, 2520.0));
        torso.addGem(new Gem(AbsoluteStatTypeEnum.CRIT_VALUE, 2520.0));
        torso.addGem(new Gem(AbsoluteStatTypeEnum.CRIT_VALUE, 2520.0));
        mage.addItem(torso, ItemSlotEnum.TORSO);

        Map<AbsoluteStatTypeEnum, Double> glovesBaseStats = new HashMap<>();
        glovesBaseStats.put(AbsoluteStatTypeEnum.DAMAGE, 1514.933);
        glovesBaseStats.put(AbsoluteStatTypeEnum.ATTACK_SPEED, 0.053);
        glovesBaseStats.put(AbsoluteStatTypeEnum.CRIT_VALUE, 1494.107);
        SetItem gloves = new SetItem("Mighty Wrathful Seeker's Gloves", ItemTypeEnum.GLOVES, glovesBaseStats, SetTypeEnum.SET1);
        gloves.addEnchant(new Enchant(EnchantTypeEnum.DAMAGE, 0.44743));
        gloves.addEnchant(new Enchant(EnchantTypeEnum.DAMAGE, 0.44768));
        gloves.addEnchant(new Enchant(EnchantTypeEnum.DAMAGE, 0.44738));
        gloves.addEnchant(new Enchant(EnchantTypeEnum.DAMAGE, 0.44766));
        gloves.addGem(new Gem(AbsoluteStatTypeEnum.CRIT_VALUE, 2520.0));
        gloves.addGem(new Gem(AbsoluteStatTypeEnum.CRIT_VALUE, 2520.0));
        gloves.addGem(new Gem(AbsoluteStatTypeEnum.CRIT_VALUE, 2520.0));
        gloves.addGem(new Gem(AbsoluteStatTypeEnum.CRIT_VALUE, 2520.0));
        gloves.addGem(new Gem(AbsoluteStatTypeEnum.CRIT_VALUE, 2520.0));
        gloves.addGem(new Gem(AbsoluteStatTypeEnum.CRIT_VALUE, 2520.0));
        gloves.addGem(new Gem(AbsoluteStatTypeEnum.CRIT_VALUE, 2520.0));
        gloves.addGem(new Gem(AbsoluteStatTypeEnum.CRIT_VALUE, 2520.0));
        gloves.addGem(new Gem(AbsoluteStatTypeEnum.CRIT_VALUE, 2520.0));
        gloves.addGem(new Gem(AbsoluteStatTypeEnum.CRIT_VALUE, 2520.0));
        mage.addItem(gloves, ItemSlotEnum.GLOVES);

        Map<AbsoluteStatTypeEnum, Double> bootsBaseStats = new HashMap<>();
        bootsBaseStats.put(AbsoluteStatTypeEnum.DAMAGE, 1510.415);
        bootsBaseStats.put(AbsoluteStatTypeEnum.MOVEMENT_SPEED, 1.113);
        bootsBaseStats.put(AbsoluteStatTypeEnum.CRIT_VALUE, 1168.091);
        SetItem boots = new SetItem("Mighty Wrathful Seeker's Boots", ItemTypeEnum.BOOTS, bootsBaseStats, SetTypeEnum.SET1);
        boots.addEnchant(new Enchant(EnchantTypeEnum.DAMAGE, 0.44760));
        boots.addEnchant(new Enchant(EnchantTypeEnum.DAMAGE, 0.44763));
        boots.addEnchant(new Enchant(EnchantTypeEnum.DAMAGE, 0.44762));
        boots.addEnchant(new Enchant(EnchantTypeEnum.DAMAGE, 0.44751));
        boots.addGem(new Gem(AbsoluteStatTypeEnum.MOVEMENT_SPEED, 0.17));
        boots.addGem(new Gem(AbsoluteStatTypeEnum.MOVEMENT_SPEED, 0.17));
        boots.addGem(new Gem(AbsoluteStatTypeEnum.MOVEMENT_SPEED, 0.17));
        boots.addGem(new Gem(AbsoluteStatTypeEnum.MOVEMENT_SPEED, 0.17));
        boots.addGem(new Gem(AbsoluteStatTypeEnum.MOVEMENT_SPEED, 0.17));
        boots.addGem(new Gem(AbsoluteStatTypeEnum.MOVEMENT_SPEED, 0.17));
        boots.addGem(new Gem(AbsoluteStatTypeEnum.MOVEMENT_SPEED, 0.17));
        boots.addGem(new Gem(AbsoluteStatTypeEnum.CRIT_VALUE, 2520.0));
        boots.addGem(new Gem(AbsoluteStatTypeEnum.CRIT_VALUE, 2520.0));
        boots.addGem(new Gem(AbsoluteStatTypeEnum.CRIT_VALUE, 2520.0));
        mage.addItem(boots, ItemSlotEnum.BOOTS);

        Map<AbsoluteStatTypeEnum, Double> twoHandBaseStats = new HashMap<>();
        twoHandBaseStats.put(AbsoluteStatTypeEnum.DAMAGE, 24570.982);
        twoHandBaseStats.put(AbsoluteStatTypeEnum.CRIT_VALUE, 3321.515);
        Map<AbsoluteStatTypeEnum, Double> twoHandUniqueBaseStats = new HashMap<>();
        twoHandUniqueBaseStats.put(AbsoluteStatTypeEnum.ATTACK_SPEED, 0.102);
        UniqueItem twoHand = new UniqueItem("Grimace of the Thunder Beast", ItemTypeEnum.TWO_HAND_WEAPON, twoHandBaseStats, twoHandUniqueBaseStats, List.of(), List.of());
        twoHand.addEnchant(new Enchant(EnchantTypeEnum.DAMAGE, 0.44776));
        twoHand.addEnchant(new Enchant(EnchantTypeEnum.DAMAGE, 0.44776));
        twoHand.addEnchant(new Enchant(EnchantTypeEnum.DAMAGE, 0.44776));
        twoHand.addEnchant(new Enchant(EnchantTypeEnum.DAMAGE, 0.44776));
        twoHand.addGem(new Gem(AbsoluteStatTypeEnum.DAMAGE, 700.0));
        twoHand.addGem(new Gem(AbsoluteStatTypeEnum.DAMAGE, 700.0));
        twoHand.addGem(new Gem(AbsoluteStatTypeEnum.DAMAGE, 700.0));
        twoHand.addGem(new Gem(AbsoluteStatTypeEnum.DAMAGE, 700.0));
        twoHand.addGem(new Gem(AbsoluteStatTypeEnum.DAMAGE, 700.0));
        twoHand.addGem(new Gem(AbsoluteStatTypeEnum.DAMAGE, 700.0));
        twoHand.addGem(new Gem(AbsoluteStatTypeEnum.DAMAGE, 700.0));
        twoHand.addGem(new Gem(AbsoluteStatTypeEnum.DAMAGE, 700.0));
        twoHand.addGem(new Gem(AbsoluteStatTypeEnum.DAMAGE, 700.0));
        twoHand.addGem(new Gem(AbsoluteStatTypeEnum.DAMAGE, 700.0));
        mage.addItem(twoHand, ItemSlotEnum.TWO_HAND_WEAPON);

        RuneTrinket runeTrinket1 = new RuneTrinket();
        runeTrinket1.addRune(new Rune("Rune of Vigor", OverallRelativeBuffTypeEnum.DAMAGE, 0.065));
        runeTrinket1.addRune(new Rune("Rune of Vigor", OverallRelativeBuffTypeEnum.DAMAGE, 0.065));
        runeTrinket1.addRune(new Rune("Rune of Vigor", OverallRelativeBuffTypeEnum.DAMAGE, 0.065));
        runeTrinket1.addRune(new Rune("Rune of Vigor", OverallRelativeBuffTypeEnum.DAMAGE, 0.065));
        runeTrinket1.addRune(new Rune("Rune of Vigor", OverallRelativeBuffTypeEnum.DAMAGE, 0.065));
        runeTrinket1.addRune(new Rune("Rune of Devastation", OverallRelativeBuffTypeEnum.CRIT_VALUE, 0.065));
        runeTrinket1.addRune(new Rune("Rune of Devastation", OverallRelativeBuffTypeEnum.CRIT_VALUE, 0.065));
        runeTrinket1.addRune(new Rune("Rune of Devastation", OverallRelativeBuffTypeEnum.CRIT_VALUE, 0.065));
        runeTrinket1.addRune(new Rune("Rune of Devastation", OverallRelativeBuffTypeEnum.CRIT_VALUE, 0.065));
        runeTrinket1.addRune(new Rune("Rune of Devastation", OverallRelativeBuffTypeEnum.CRIT_VALUE, 0.065));
        mage.addRuneTrinket(runeTrinket1, 1);

        RuneTrinket runeTrinket2 = new RuneTrinket();
        runeTrinket2.addRune(new SpecialRune("Concentrated Spring Rune", Map.of(OverallRelativeBuffTypeEnum.HEALTH_POINTS, 0.065, OverallRelativeBuffTypeEnum.CRIT_VALUE, 0.065, OverallRelativeBuffTypeEnum.ATTACK_SPEED, 0.065), ""));
        runeTrinket2.addRune(new SpecialRune("Concentrated Spring Rune", Map.of(OverallRelativeBuffTypeEnum.HEALTH_POINTS, 0.065, OverallRelativeBuffTypeEnum.CRIT_VALUE, 0.065, OverallRelativeBuffTypeEnum.ATTACK_SPEED, 0.065), ""));
        runeTrinket2.addRune(new SpecialRune("Concentrated Spring Rune", Map.of(OverallRelativeBuffTypeEnum.HEALTH_POINTS, 0.065, OverallRelativeBuffTypeEnum.CRIT_VALUE, 0.065, OverallRelativeBuffTypeEnum.ATTACK_SPEED, 0.065), ""));
        runeTrinket2.addRune(new SpecialRune("Concentrated Spring Rune", Map.of(OverallRelativeBuffTypeEnum.HEALTH_POINTS, 0.065, OverallRelativeBuffTypeEnum.CRIT_VALUE, 0.065, OverallRelativeBuffTypeEnum.ATTACK_SPEED, 0.065), ""));
        runeTrinket2.addRune(new SpecialRune("Concentrated Spring Rune", Map.of(OverallRelativeBuffTypeEnum.HEALTH_POINTS, 0.065, OverallRelativeBuffTypeEnum.CRIT_VALUE, 0.065, OverallRelativeBuffTypeEnum.ATTACK_SPEED, 0.065), ""));
        runeTrinket2.addRune(new SpecialRune("Concentrated Summer Rune", Map.of(OverallRelativeBuffTypeEnum.RESISTANCE, 0.065, OverallRelativeBuffTypeEnum.DAMAGE, 0.065, OverallRelativeBuffTypeEnum.BLOCK_VALUE, 0.065), ""));
        runeTrinket2.addRune(new SpecialRune("Concentrated Summer Rune", Map.of(OverallRelativeBuffTypeEnum.RESISTANCE, 0.065, OverallRelativeBuffTypeEnum.DAMAGE, 0.065, OverallRelativeBuffTypeEnum.BLOCK_VALUE, 0.065), ""));
        runeTrinket2.addRune(new SpecialRune("Concentrated Summer Rune", Map.of(OverallRelativeBuffTypeEnum.RESISTANCE, 0.065, OverallRelativeBuffTypeEnum.DAMAGE, 0.065, OverallRelativeBuffTypeEnum.BLOCK_VALUE, 0.065), ""));
        runeTrinket2.addRune(new Rune("Rune of Resilience", OverallRelativeBuffTypeEnum.RESISTANCE, 0.065));
        runeTrinket2.addRune(new SpecialRune("Rune of Rising Vigor", Map.of(OverallRelativeBuffTypeEnum.MOVEMENT_SPEED, 0.10, OverallRelativeBuffTypeEnum.ATTACK_SPEED, 0.06), ""));
        mage.addRuneTrinket(runeTrinket2, 2);

        RuneTrinket runeTrinket3 = new RuneTrinket();
        runeTrinket3.addRune(new SpecialRune("Concentrated Autumn Rune", Map.of(OverallRelativeBuffTypeEnum.ANDERMANT_DROP_BONUS, 0.05, OverallRelativeBuffTypeEnum.MOVEMENT_SPEED, 0.065, OverallRelativeBuffTypeEnum.DAMAGE, 0.065), ""));
        runeTrinket3.addRune(new SpecialRune("Concentrated Autumn Rune", Map.of(OverallRelativeBuffTypeEnum.ANDERMANT_DROP_BONUS, 0.05, OverallRelativeBuffTypeEnum.MOVEMENT_SPEED, 0.065, OverallRelativeBuffTypeEnum.DAMAGE, 0.065), ""));
        runeTrinket3.addRune(new SpecialRune("Concentrated Autumn Rune", Map.of(OverallRelativeBuffTypeEnum.ANDERMANT_DROP_BONUS, 0.05, OverallRelativeBuffTypeEnum.MOVEMENT_SPEED, 0.065, OverallRelativeBuffTypeEnum.DAMAGE, 0.065), ""));
        runeTrinket3.addRune(new SpecialRune("Concentrated Autumn Rune", Map.of(OverallRelativeBuffTypeEnum.ANDERMANT_DROP_BONUS, 0.05, OverallRelativeBuffTypeEnum.MOVEMENT_SPEED, 0.065, OverallRelativeBuffTypeEnum.DAMAGE, 0.065), ""));
        runeTrinket3.addRune(new SpecialRune("Concentrated Autumn Rune", Map.of(OverallRelativeBuffTypeEnum.ANDERMANT_DROP_BONUS, 0.05, OverallRelativeBuffTypeEnum.MOVEMENT_SPEED, 0.065, OverallRelativeBuffTypeEnum.DAMAGE, 0.065), ""));
        runeTrinket3.addRune(new SpecialRune("Concentrated Solstice Rune", Map.of(OverallRelativeBuffTypeEnum.ICE_RESISTANCE, 0.065, OverallRelativeBuffTypeEnum.HEALTH_POINTS, 0.065, OverallRelativeBuffTypeEnum.CRIT_VALUE, 0.065), ""));
        runeTrinket3.addRune(new SpecialRune("Concentrated Solstice Rune", Map.of(OverallRelativeBuffTypeEnum.ICE_RESISTANCE, 0.065, OverallRelativeBuffTypeEnum.HEALTH_POINTS, 0.065, OverallRelativeBuffTypeEnum.CRIT_VALUE, 0.065), ""));
        runeTrinket3.addRune(new SpecialRune("Concentrated Solstice Rune", Map.of(OverallRelativeBuffTypeEnum.ICE_RESISTANCE, 0.065, OverallRelativeBuffTypeEnum.HEALTH_POINTS, 0.065, OverallRelativeBuffTypeEnum.CRIT_VALUE, 0.065), ""));
        runeTrinket3.addRune(new SpecialRune("Concentrated Solstice Rune", Map.of(OverallRelativeBuffTypeEnum.ICE_RESISTANCE, 0.065, OverallRelativeBuffTypeEnum.HEALTH_POINTS, 0.065, OverallRelativeBuffTypeEnum.CRIT_VALUE, 0.065), ""));
        runeTrinket3.addRune(new SpecialRune("Concentrated Solstice Rune", Map.of(OverallRelativeBuffTypeEnum.ICE_RESISTANCE, 0.065, OverallRelativeBuffTypeEnum.HEALTH_POINTS, 0.065, OverallRelativeBuffTypeEnum.CRIT_VALUE, 0.065), ""));
        mage.addRuneTrinket(runeTrinket3, 3);

        RuneTrinket runeTrinket4 = new RuneTrinket();
        runeTrinket4.addRune(new Rune("Rune of Celerity", OverallRelativeBuffTypeEnum.ATTACK_SPEED, 0.065));
        runeTrinket4.addRune(new Rune("Rune of Celerity", OverallRelativeBuffTypeEnum.ATTACK_SPEED, 0.065));
        runeTrinket4.addRune(new Rune("Rune of Celerity", OverallRelativeBuffTypeEnum.ATTACK_SPEED, 0.065));
        runeTrinket4.addRune(new Rune("Rune of Celerity", OverallRelativeBuffTypeEnum.ATTACK_SPEED, 0.065));
        runeTrinket4.addRune(new Rune("Rune of Celerity", OverallRelativeBuffTypeEnum.ATTACK_SPEED, 0.065));
        runeTrinket4.addRune(new Rune("Rune of Vitality", OverallRelativeBuffTypeEnum.HEALTH_POINTS, 0.065));
        runeTrinket4.addRune(new Rune("Rune of Vitality", OverallRelativeBuffTypeEnum.HEALTH_POINTS, 0.065));
        runeTrinket4.addRune(new Rune("Rune of Vitality", OverallRelativeBuffTypeEnum.HEALTH_POINTS, 0.065));
        runeTrinket4.addRune(new Rune("Rune of Vitality", OverallRelativeBuffTypeEnum.HEALTH_POINTS, 0.065));
        runeTrinket4.addRune(new Rune("Rune of Vitality", OverallRelativeBuffTypeEnum.HEALTH_POINTS, 0.065));
        mage.addRuneTrinket(runeTrinket4, 4);

        RuneTrinket runeTrinket5 = new RuneTrinket();
        runeTrinket5.addRune(new Rune("Rune of Fortitude", OverallRelativeBuffTypeEnum.ARMOR, 0.065));
        runeTrinket5.addRune(new Rune("Rune of Fortitude", OverallRelativeBuffTypeEnum.ARMOR, 0.065));
        runeTrinket5.addRune(new Rune("Rune of Fortitude", OverallRelativeBuffTypeEnum.ARMOR, 0.065));
        runeTrinket5.addRune(new SpecialRune("Rune of the Realm Changer", Map.of(), "Increases the Realm Changer talent by 5."));
        runeTrinket5.addRune(new SpecialRune("Rune of the Andermant Fever", Map.of(), "Increases the Andermant Fever talent by 5."));
        runeTrinket5.addRune(new Rune("Rune of Acceleration", OverallRelativeBuffTypeEnum.MOVEMENT_SPEED, 0.065));
        runeTrinket5.addRune(new Rune("Rune of Acceleration", OverallRelativeBuffTypeEnum.MOVEMENT_SPEED, 0.065));
        runeTrinket5.addRune(new Rune("Rune of Materi Blessing", OverallRelativeBuffTypeEnum.MATERI_FRAGMENT_DROP_BONUS, 0.3));
        runeTrinket5.addRune(new Rune("Rune of Materi Blessing", OverallRelativeBuffTypeEnum.MATERI_FRAGMENT_DROP_BONUS, 0.3));
        runeTrinket5.addRune(new Rune("Rune of Materi Blessing", OverallRelativeBuffTypeEnum.MATERI_FRAGMENT_DROP_BONUS, 0.3));
        mage.addRuneTrinket(runeTrinket5, 5);

        JewelTrinket jewelTrinket1 = new JewelTrinket();
        jewelTrinket1.addJewel(new Jewel("Jewel of Eternal Scorn", OverallRelativeBuffTypeEnum.CRIT_VALUE, 0.15, "..."));
        jewelTrinket1.addJewel(new Jewel("Jewel of Rage", "..."));
        jewelTrinket1.addJewel(new Jewel("Jewel of Amplified Healing", "..."));
        jewelTrinket1.addJewel(new Jewel("Jewel of the Frozen Heart", "..."));
        jewelTrinket1.addJewel(new Jewel("Jewel of the Easter Fever", "..."));
        jewelTrinket1.addJewel(new Jewel("Jewel of the Gem Fortune", "..."));
        jewelTrinket1.addJewel(new Jewel("Jewel of the Eternal Wrath", "..."));
        jewelTrinket1.addJewel(new Jewel("Jewel of the Ingredient Hunter", "..."));
        jewelTrinket1.addJewel(new Jewel("Jewel of the Ingredient Hunter", "..."));
        jewelTrinket1.addJewel(new Jewel("Jewel of the Ingredient Hunter", "..."));
        mage.addJewelTrinket(jewelTrinket1, 1);

        JewelTrinket jewelTrinket2 = new JewelTrinket();
        jewelTrinket2.addJewel(new Jewel("Jewel of Focus", "..."));
        jewelTrinket2.addJewel(new Jewel("Jewel of Focus", "..."));
        jewelTrinket2.addJewel(new Jewel("Jewel of Focus", "..."));
        jewelTrinket2.addJewel(new Jewel("Jewel of Focus", "..."));
        jewelTrinket2.addJewel(new Jewel("Jewel of Focus", "..."));
        jewelTrinket2.addJewel(new Jewel("Jewel of Vigor", OverallRelativeBuffTypeEnum.DAMAGE, 0.1));
        jewelTrinket2.addJewel(new Jewel("Jewel of Ambidextrous Vigor", OverallRelativeBuffTypeEnum.TWO_HAND_DAMAGE, 0.1));
        jewelTrinket2.addJewel(new Jewel("Jewel of Vitality", OverallRelativeBuffTypeEnum.HEALTH_POINTS, 0.1));
        jewelTrinket2.addJewel(new Jewel("Jewel of Encouragement", "..."));
        jewelTrinket2.addJewel(new Jewel("Jewel of Contribution", "..."));
        mage.addJewelTrinket(jewelTrinket2, 2);

        JewelTrinket jewelTrinket3 = new JewelTrinket();
        jewelTrinket3.addJewel(new Jewel("Jewel of Lasting Health", "..."));
        jewelTrinket3.addJewel(new Jewel("Jewel of Converse", "..."));
        jewelTrinket3.addJewel(new Jewel("Fiery Flower Jewel", "..."));
        jewelTrinket3.addJewel(new Jewel("Jewel of Strenuousness", "..."));
        jewelTrinket3.addJewel(new Jewel("Jewel of Fortitude", OverallRelativeBuffTypeEnum.ARMOR, 0.1));
        jewelTrinket3.addJewel(new Jewel("Jewel of Prolongation", "..."));
        jewelTrinket3.addJewel(new Jewel("Jewel of Revival Boon", "..."));
        jewelTrinket3.addJewel(new Jewel("Jewel of Pent-up-Power", "..."));
        jewelTrinket3.addJewel(new Jewel("Jewel of Scorching Ray", "..."));
        mage.addJewelTrinket(jewelTrinket3, 3);

        mage.setEssence(0.50);

        return mage;
    }

    public static void printStats(Map<AbsoluteStatTypeEnum, Double> stats)
    {
        System.out.println("Character:");
        System.out.printf(AbsoluteStatTypeEnum.DAMAGE + ": %.2f%n", stats.get(AbsoluteStatTypeEnum.DAMAGE));
        System.out.printf(AbsoluteStatTypeEnum.ATTACK_SPEED + ": %.2f%n", stats.get(AbsoluteStatTypeEnum.ATTACK_SPEED));
        System.out.printf(AbsoluteStatTypeEnum.CRIT_VALUE + ": %.2f%n", stats.get(AbsoluteStatTypeEnum.CRIT_VALUE));
        System.out.printf(AbsoluteStatTypeEnum.MANA + ": %.2f%n", stats.get(AbsoluteStatTypeEnum.MANA));
        System.out.printf(AbsoluteStatTypeEnum.MANA_PER_SECOND + ": %.2f%n", stats.get(AbsoluteStatTypeEnum.MANA_PER_SECOND));
        System.out.printf(AbsoluteStatTypeEnum.MOVEMENT_SPEED + ": %.2f%n", stats.get(AbsoluteStatTypeEnum.MOVEMENT_SPEED));
        System.out.printf(AbsoluteStatTypeEnum.HEALTH_POINTS + ": %.2f%n", stats.get(AbsoluteStatTypeEnum.HEALTH_POINTS));
        System.out.printf(AbsoluteStatTypeEnum.HEALTH_PER_SECOND + ": %.2f%n", stats.get(AbsoluteStatTypeEnum.HEALTH_PER_SECOND));
        System.out.printf(AbsoluteStatTypeEnum.BLOCK_VALUE + ": %.2f%n", stats.get(AbsoluteStatTypeEnum.BLOCK_VALUE));
        System.out.printf(AbsoluteStatTypeEnum.ARMOR + ": %.2f%n", stats.get(AbsoluteStatTypeEnum.ARMOR));
        System.out.printf(AbsoluteStatTypeEnum.FIRE_RESISTANCE + ": %.2f%n", stats.get(AbsoluteStatTypeEnum.FIRE_RESISTANCE));
        System.out.printf(AbsoluteStatTypeEnum.ICE_RESISTANCE + ": %.2f%n", stats.get(AbsoluteStatTypeEnum.ICE_RESISTANCE));
        System.out.printf(AbsoluteStatTypeEnum.LIGHTNING_RESISTANCE + ": %.2f%n", stats.get(AbsoluteStatTypeEnum.LIGHTNING_RESISTANCE));
        System.out.printf(AbsoluteStatTypeEnum.ANDERMAGIC_RESISTANCE + ": %.2f%n", stats.get(AbsoluteStatTypeEnum.ANDERMAGIC_RESISTANCE));
        System.out.printf(AbsoluteStatTypeEnum.POISON_RESISTANCE + ": %.2f%n", stats.get(AbsoluteStatTypeEnum.POISON_RESISTANCE));
    }
}