package com.langleon.dsobuildsim.wisdomskilltree.wisdomskill;

public enum WisdomSkillType {

    RISING_VIGOR,
    VIVACIOUS_VITALITY,
    CONJURED_DISTILLATION,
    RISING_POWER,
    DECISIVE_STRIKE,
    HANGMANS_PRIDE,
    STURDY_SHIELD,
    HARD_AS_A_ROCK,
    ELEMENTAL_PROTECTION,
    SECOND_CHANCE,
    EMERGENCY_RESERVES,
    ENERGETIC_FORCE,
    DEXTROUS_SMITING,
    DEXTROUS_AGILITY,
    A_HANDFUL_OF_RESOURCES,
    AMBIDEXTROUS_SMITING,
    AMBIDEXTROUS_AGILITY,
    LIFETIME_THIEF,
    BONANZA,
    PEDDLER,
    PORTABLE_WORKBENCH,
    HOME_SWEET_HOME,
    ON_HORSEBACK,
    RACING_SLIPPERS,
    ;
}
