package com.langleon.dsobuildsim.enums.pets;

public enum PetType {
    //Dragon Spawn
    BLUE_DRAGONSPAWN("Blue Dragonspawn"),
    SILVER_SCALED_DRAGONSPAWN("Silver-Scaled Dragonspawn"),
    COPPER_SCALED_DRAGONSPAWN("Copper-Sclaed Dragonspawn"),
    DRAGONSPAWN("Dragonspawn"),
    SPINEY_DRAGONSPAWN("Spiney Dragonspawn"),
    LITTLE_DRAGONSPAWN("Little Dragonspawn"),
    FIRE_SCALED_DRAGONSPAWN("Fire-Sclaed Dragonspawn"),
    EMBER_SCALED_DRAGONSPAWN("EmberScaled Dragonspawn"),
    BRIGHTLY_SCALED_DRAGONSPAWN("Brightly Scaled Dragonspawn"),
    EMERALD_SCALED_DRAGONSPAWN("Emerald-Scaled Dragonspawn"),
    PUDGY_DRAGONSPAWN("Pudgy Dragonspawn"),

    //Scoundrels
    BATTY_GREMLIN("Batty Gremlin"),
    GOTH_HARE("Goth Hare"),
    HORNED_FIRE_GOBLIN("Horned Fire Goblin"),
    JUMPING_JACK_O_LANTERN("Jumping Jack-O'-Lantern"),
    TINY_TROUBLEMAKER("Tiny Troublemaker"),
    TINY_TROUBLEMAKER_LUXURIANT("Tiny Troublemaker-Luxuriant"),
    TINY_TROUBLEMAKER_ELEGANT("Tiny Troublemaker-Elegant"),
    TINY_TROUBLEMAKER_LOVELY("Tiny Troublemaker-Lovely"),
    TINY_TROUBLEMAKER_VIVID("Tiny Troublemaker-Vivid"),
    TINY_TROUBLEMAKER_TALENTED("Tiny Troublemaker-Talented"),
    TINY_TROUBLEMAKER_SUPERSTAR("Tiny Troublemaker-Superstar"),
    TINY_TROUBLEMAKER_DAZZLING("Tiny Troublemaker-Dazzling"),
    TINY_TROUBLEMAKER_CHARMING("Tiny Troublemaker-Charming"),
    LIVING_SKULL("Living Skull"),
    PIRATE_KINGS_SCULL("Pirate King's Skull"),
    MAD_EYE_SKULLY("Mad Eye Skully"),
    LANKY_FIRE_GNOME("Lanky Fire Gnome"),
    BOLSTERED_FIRE_GNOME("Bolstered Fire Gnome"),

    //Domesticated
    HACHI_DOG("Hachi Dog"),
    MELON_PUG("Melon Pug"),
    FAWN_KITTEN("Fawn Kitten"),
    WONDER_MUTT("Wonder Mutt"),
    LITTLE_IRUSAN("Little Irusan"),
    BLACK_CHICKEN("Black Chicken"),
    BROWN_CHICKEN("Brown Chicken"),
    WHITE_CHICKEN("White Chicken"),
    AVIATOR_CHICKEN("Aviator Chicken"),
    PROUD_BILLY_GOAT("Proud Billy Goat"),
    JINDO("Jindo"),
    CUTE_DOGGY("Cute Doggy"),
    HOPPY_BUNNY("Hoppy Bunny"),

    //Wild Beasts
    GREEN_RAPTOR("Green Raptor"),
    MUTANT_RAT("Mutant Rat"),
    CHEEKY_MONKEY("Cheeky Monkey"),
    LITTLE_RAPTOR("Little Raptor"),
    FENNEC("Fennec"),
    RHINO_CALF("Rhino Calf"),
    FANCY_RAT("Fancy Rat"),
    RAT_KING("Rat King"),
    LITTLE_GOLDEN_GOOSE("Little Golden Goose"),

    //Aquatics
    BUG_COLLECTING_JABBAX("Bug-collecting Jabbax"),
    TENACIOUS_DRAGON_TURTLE("Tenacious Dragon Turtle"),
    SILVER_DRAGON_TURTLE("Silver Dragon Turtle"),
    GOLDEN_DRAGON_TURTLE("Golden Dragon Turtle"),
    LOVING_KRAKEN("Loving Kraken"),
    BLUE_PAUL("Blue Paul"),
    PINK_PAUL("Pink Paul"),
    GREEN_PAUL("Green Paul"),
    BLACK_PAUL("Black Paul"),
    WHITE_PAUL("White Paul"),
    YELLOW_PAUL("Yellow Paul"),

    //Avians
    SAPPHIRE_PARROT("Sapphire Parrot"),
    RUBY_PARROT("Ruby Parrot"),
    EMERALD_PARROT("Emerald Parrot"),
    GOLDEN_PARROT("Golden Parrot"),
    SHARP_EYED_RAVEN("Sharp-eyed Raven"),
    FIRE_ROOSTER("Fire Rooster"),
    GRIM_RAVEN("Grim Raven"),

    //Tamed Foes
    MOLTEN_FIRE_GUARD("Molten Fire Guard"),
    JUMPY_SQUIRE("Jumpy Squire"),
    VARNOK_ACTION_FIGURE("Varnok Action Figure (TM)"),
    BEARSERKER("Bearserker"),
    EVIL_EYE("Evil Eye"),
    TYKE_CLOPS("Tyke Clops"),
    GREMLIN_SQUIRE("Gremlin Squire"),
    GOLD_SQUIRE("Gold Squire"),
    HEREDUR_DOLL("Heredur Doll"),
    BEARACH_DOLL("Bearach Doll"),
    MEDUSA_DOLL("M'edusa Doll"),
    PROFESSOR_JULLOV("Professor Jullov"),
    ARACHNA_DOLL("Arachna Doll"),
    CYCLOPS_KID("Cyclops Kid"),
    WINTER_GNOME("Winter Gnome"),
    NEFATARI_DOLL("Nefatari Doll"),
    ASAR_DOLL("Asar Doll"),
    BLOODMAGE_DOLL("Bloodmage Doll"),
    KARABOSSA_DOLL("Karabossa Doll"),
    MAGOTINA_DOLL("Magotina Doll"),
    NIAN_BEAST_DOLL("Nian Beast Doll"),
    DEATH_WINK("Death Wink"),
    DRAGAN_DOLL("Dragan Doll"),
    MORTIS_AND_SKELEDRAGON_DOLL("Mortis and Skeledragon Doll"),
    MORTIS_DOLL("Mortis Doll"),
    SARGON_DOLL("Sargon Doll"),
    UNLEASHED_SARGON_DOLL("Unleashed Sargon Doll"),
    CAKE_MEANIE("Cake Meanie"),
    CAKE_BOSS("Cake Boss"),
    THE_DARK_NIGHTS_DEPENDENTS("The Dark Nights Dependents"),
    THE_END_OF_DRAGAN_DOLL("The End of Dragan Doll"),
    THE_SOUL_OF_DRAGAN_DOLL("The Soul of Dragan Doll"),
    GUARDIAN_OF_RAVENCAW("Guardian of Ravencaw"),

    //Free Spirits
    THE_MARVELLOUS_JULIO_BOBR("The marvellous Julio Bóbr"),
    JULIO_BOBR("Julio Bóbr"),
    COLORFUL_FIREFLY("Colorful Firefly"),
    GOLDEN_PHOENIX("Golden Phoenix"),
    WINTER_SOLSTICE_ELF("Winter Solstice Elf"),
    GOLD_FAIRY("Gold Fairy"),
    BLAZING_PHOENIX("Blazing Phoenix"),
    FAIRY("Fairy"),
    DAZZLING_FIREFLY("Dazzling Firefly"),
    DILIGENT_GNOME("Diligent Gnome"),
    TEMPEST_PHOENIX("Tempest Phoenix"),
    SWAN_MAIDEN("Swan Maiden"),
    SWIFT_HARPY("Swift Harpy"),
    TREASURE_COLLECTOR("Treasure Collector"),
    GLOOMY_HARPY_HP1("Gloomy Harpy"),
    GLOOMY_HARPY_HP2("Gloomy Harpy"),
    GLOOMY_HARPY_CRIT1("Gloomy Harpy"),
    GLOOMY_HARPY_CRIT2("Gloomy Harpy"),
    GLOOMY_HARPY_MS1("Gloomy Harpy"),
    GLOOMY_HARPY_MS2("Gloomy Harpy"),
    GLOOMY_HARPY_CRIT3("Gloomy Harpy"),
    GLOOMY_HARPY_CRIT4("Gloomy Harpy"),
    GLOOMY_HARPY_ARMOR1("Gloomy Harpy"),
    GLOOMY_HARPY_ARMOR2("Gloomy Harpy"),
    GLOOMY_HARPY_XP("Gloomy Harpy"),
    GLOOMY_HARPY_MSCITY1("Gloomy Harpy"),
    GLOOMY_HARPY_MSCITY2("Gloomy Harpy"),

    //Automatons
    BLACK_ESSENCE_SPROUT("Black Essence Sprout"),
    WINTER_SNOWMAN("Winter Snowman"),
    SUPREME_SNOWMAN("Supreme Snowman"),
    WHITE_ESSENCE_SPROUT("White Essence Sprout"),
    BOMB_BUDDY("Bomb Buddy"),
    GREEN_ESSENCE_SPROUT("Green Essence Sprout"),
    BLUE_ESSENCE_SPROUT("Blue Essence Sprout"),
    PURPLE_ESSENCE_SPROUT("Purple Essence Sprout"),
    YELLOW_ESSENCE_SPROUT("Yellow Essence Sprout"),
    RED_ESSENCE_SPROUT("Red Essence Sprout"),
    WEE_VISCANIUM_GUARDIAN("Wee Viscanium Guardian"),

    //Lucky Cats
    BRONZE_LUCKY_CAT("Bronze Lucky Cat"),
    SILVERED_LUCKY_CAT("Silvered Lucky Cat"),
    GILDED_LUCKY_CAT("Gilded Lucky Cat"),
    SUNGLASSES_LUCKY_CAT("Sunglasses Lucky Cat"),

    //Enigmatic Hatchlings
    VIGOROUS_ENIGMATIC_HATCHLING("Vigorous Enigmatic Hatchling"),
    GALLANT_ENIGMATIC_HATCHLING("Gallant Enigmatic Hatchling"),
    DETERMINED_ENIGMATIC_HATCHLING("Determined Enigmatic Hatchling"),
    SWIFT_ENIGMATIC_HATCHLING("Swift Enigmatic Hatchling"),
    FIERY_ENIGMATIC_HATCHLING("Fiery Enigmatic Hatchling"),
    COLD_HEARTED_ENIGMATIC_HATCHLING("Cold-hearted Enigmatic Hatchling"),
    NOXIOUS_ENIGMATIC_HATCHLING("Noxious Enigmatic Hatchling"),
    THUNDEROUS_ENIGMATIC_HATCHLING("Thunderous Enigmatic Hatchling"),
    SINISTER_ENIGMATIC_HATCHLING("Sinister Enigmatic Hatchling"),
    SPIKY_ENIGMATIC_HATCHLING("Spiky Enigmatic Hatchling"),
    BUNNY_HATCH("Bunny Hatch"),
    CRACKED_COMPANION("Cracked Companion"),
    SUPER_THUMPER("Super Thumper"),

    //Awoken Lion
    AWOKEN_LION("Awoken Lion"),
    BLUE_AWOKEN_LION("Blue Awoken Lion"),
    BLACK_AWOKEN_LION("Black Awoken Lion"),
    KUNG_FU_LION("Kung Fu Lion"),

    //Ancient Dragons
    BLOOD_CLAW_DRAGON("Blood Claw Dragon"),
    FIRE_CLAW_DRAGON("Fire Claw Dragon"),
    EVIL_CLAW_DRAGON("Evil Claw Dragon"),
    WILD_CLAW_DRAGON("Wild Claw Dragon"),
    WINTER_MAGIC_DRAGON("Winter Magic Dragon"),
    ABYSSAL_MAGIC_DRAGON("Abyssal Magic Dragon"),
    WILD_MAGIC_DRAGON("Wild Magic Dragon"),
    EMERALD_MAGIC_DRAGON("Emerald Magic Dragon"),
    PRIMITIVE_SOUL_DRAGON("Primitive Soul Dragon"),
    LIGHTNING_SOUL_DRAGON("Primitive Soul Dragon"),
    EMERALD_SOUL_DRAGON("Emerald Soul Dragon"),
    CRYSTAL_SOUL_DRAGON("Crystal Soul Dragon"),
    CRYSTAL_WING("Crystal Wing"),
    WING_OF_STRENGTH("Wing of Strength"),
    WING_OF_WISDOM("Wing of Wisdom"),
    WING_OF_MYSTERY("Wing of Mystery"),
    ;


    private final String name;

    PetType(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        return name;
    }
}
